// FitKu — Tambahan Data Makanan Indonesia (200+ item)
// Format mengikuti indonesianFoods.seed.ts yang sudah ada
// Sumber referensi: TKPI Kemenkes RI, DKBM Indonesia
// Semua nilai per porsi standar yang disebutkan di servingDescription

import { Food } from '../src/data/types/food.types';

// Helper: gunakan generateId() yang sudah ada di app
// Saat diimport ke seed file, ganti generateId() dengan id aktual

export const additionalFoods: Omit<Food, 'id'>[] = [

  // ============================================================
  // NASI & KARBO (tambahan ~25 item, dari 8 → ~33)
  // ============================================================
  {
    name: 'Nasi Padang',
    category: 'nasi_karbo',
    calories: 300,
    protein: 6,
    carbs: 65,
    fat: 2,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 centong (100g)',
  },
  {
    name: 'Bubur Ayam',
    category: 'nasi_karbo',
    calories: 180,
    protein: 10,
    carbs: 25,
    fat: 4,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (250g)',
  },
  {
    name: 'Nasi Goreng Kampung',
    category: 'nasi_karbo',
    calories: 420,
    protein: 12,
    carbs: 58,
    fat: 15,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 porsi (200g)',
  },
  {
    name: 'Nasi Goreng Seafood',
    category: 'nasi_karbo',
    calories: 450,
    protein: 18,
    carbs: 56,
    fat: 16,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 porsi (200g)',
  },
  {
    name: 'Nasi Kuning',
    category: 'nasi_karbo',
    calories: 150,
    protein: 3,
    carbs: 32,
    fat: 2,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 centong (100g)',
  },
  {
    name: 'Nasi Liwet',
    category: 'nasi_karbo',
    calories: 160,
    protein: 3,
    carbs: 33,
    fat: 3,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 centong (100g)',
  },
  {
    name: 'Nasi Bakar',
    category: 'nasi_karbo',
    calories: 280,
    protein: 8,
    carbs: 48,
    fat: 6,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 bungkus (150g)',
  },
  {
    name: 'Ketoprak',
    category: 'nasi_karbo',
    calories: 320,
    protein: 12,
    carbs: 48,
    fat: 9,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 porsi (250g)',
  },
  {
    name: 'Nasi Tim Ayam',
    category: 'nasi_karbo',
    calories: 240,
    protein: 14,
    carbs: 35,
    fat: 5,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 porsi (200g)',
  },
  {
    name: 'Bubur Kacang Hijau',
    category: 'nasi_karbo',
    calories: 210,
    protein: 8,
    carbs: 38,
    fat: 3,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (200g)',
  },
  {
    name: 'Lontong Sayur',
    category: 'nasi_karbo',
    calories: 280,
    protein: 8,
    carbs: 42,
    fat: 9,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 porsi (300g)',
  },
  {
    name: 'Nasi Lemak',
    category: 'nasi_karbo',
    calories: 200,
    protein: 4,
    carbs: 38,
    fat: 4,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 centong (100g)',
  },
  {
    name: 'Mie Rebus',
    category: 'nasi_karbo',
    calories: 280,
    protein: 9,
    carbs: 45,
    fat: 7,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 porsi (200g)',
  },
  {
    name: 'Kwetiau Goreng',
    category: 'nasi_karbo',
    calories: 380,
    protein: 13,
    carbs: 52,
    fat: 13,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 porsi (200g)',
  },
  {
    name: 'Bihun Rebus',
    category: 'nasi_karbo',
    calories: 200,
    protein: 5,
    carbs: 38,
    fat: 3,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Nasi Bakmoy',
    category: 'nasi_karbo',
    calories: 320,
    protein: 15,
    carbs: 45,
    fat: 8,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 porsi (250g)',
  },
  {
    name: 'Nasi Rames',
    category: 'nasi_karbo',
    calories: 450,
    protein: 18,
    carbs: 58,
    fat: 14,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 porsi (300g)',
  },
  {
    name: 'Spaghetti Bolognese',
    category: 'nasi_karbo',
    calories: 420,
    protein: 20,
    carbs: 52,
    fat: 14,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 porsi (250g)',
  },
  {
    name: 'Roti Tawar',
    category: 'nasi_karbo',
    calories: 80,
    protein: 3,
    carbs: 15,
    fat: 1,
    servingSize: 30,
    servingUnit: 'g',
    servingDescription: '1 lembar (30g)',
  },
  {
    name: 'Singkong Rebus',
    category: 'nasi_karbo',
    calories: 160,
    protein: 1,
    carbs: 38,
    fat: 0,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Ubi Rebus',
    category: 'nasi_karbo',
    calories: 120,
    protein: 2,
    carbs: 28,
    fat: 0,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Oatmeal',
    category: 'nasi_karbo',
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    servingSize: 40,
    servingUnit: 'g',
    servingDescription: '1 porsi kering (40g)',
  },
  {
    name: 'Roti Gandum',
    category: 'nasi_karbo',
    calories: 70,
    protein: 3,
    carbs: 13,
    fat: 1,
    servingSize: 30,
    servingUnit: 'g',
    servingDescription: '1 lembar (30g)',
  },
  {
    name: 'Jagung Rebus',
    category: 'nasi_karbo',
    calories: 130,
    protein: 3,
    carbs: 29,
    fat: 1,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 tongkol sedang (100g)',
  },
  {
    name: 'Kentang Goreng',
    category: 'nasi_karbo',
    calories: 310,
    protein: 4,
    carbs: 40,
    fat: 15,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 porsi (100g)',
  },

  // ============================================================
  // LAUK (tambahan ~35 item, dari 17 → ~52)
  // ============================================================
  {
    name: 'Ikan Goreng Gurame',
    category: 'lauk',
    calories: 220,
    protein: 28,
    carbs: 5,
    fat: 10,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 ekor sedang (100g)',
  },
  {
    name: 'Ikan Goreng Lele',
    category: 'lauk',
    calories: 190,
    protein: 25,
    carbs: 4,
    fat: 9,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 ekor sedang (100g)',
  },
  {
    name: 'Ikan Bakar Kembung',
    category: 'lauk',
    calories: 175,
    protein: 26,
    carbs: 2,
    fat: 7,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 ekor (100g)',
  },
  {
    name: 'Ikan Tongkol Goreng',
    category: 'lauk',
    calories: 200,
    protein: 30,
    carbs: 3,
    fat: 8,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Udang Goreng Tepung',
    category: 'lauk',
    calories: 240,
    protein: 18,
    carbs: 15,
    fat: 12,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '5 ekor (100g)',
  },
  {
    name: 'Cumi Goreng Tepung',
    category: 'lauk',
    calories: 220,
    protein: 16,
    carbs: 18,
    fat: 9,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 porsi (100g)',
  },
  {
    name: 'Telur Ceplok',
    category: 'lauk',
    calories: 130,
    protein: 9,
    carbs: 1,
    fat: 10,
    servingSize: 55,
    servingUnit: 'g',
    servingDescription: '1 butir (55g)',
  },
  {
    name: 'Telur Rebus',
    category: 'lauk',
    calories: 77,
    protein: 6,
    carbs: 1,
    fat: 5,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '1 butir (50g)',
  },
  {
    name: 'Telur Dadar',
    category: 'lauk',
    calories: 150,
    protein: 10,
    carbs: 2,
    fat: 12,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 lembar (60g)',
  },
  {
    name: 'Tahu Goreng',
    category: 'lauk',
    calories: 110,
    protein: 8,
    carbs: 4,
    fat: 7,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 potong besar (80g)',
  },
  {
    name: 'Tempe Goreng',
    category: 'lauk',
    calories: 160,
    protein: 11,
    carbs: 10,
    fat: 9,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 potong besar (80g)',
  },
  {
    name: 'Tempe Bacem',
    category: 'lauk',
    calories: 175,
    protein: 11,
    carbs: 14,
    fat: 8,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 potong (80g)',
  },
  {
    name: 'Tahu Bacem',
    category: 'lauk',
    calories: 120,
    protein: 8,
    carbs: 8,
    fat: 6,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 potong (80g)',
  },
  {
    name: 'Rendang Sapi',
    category: 'lauk',
    calories: 290,
    protein: 26,
    carbs: 6,
    fat: 18,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
    regionTag: 'Padang',
  },
  {
    name: 'Daging Sapi Goreng',
    category: 'lauk',
    calories: 250,
    protein: 28,
    carbs: 3,
    fat: 14,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Ayam Goreng Krispy',
    category: 'lauk',
    calories: 320,
    protein: 22,
    carbs: 18,
    fat: 18,
    servingSize: 120,
    servingUnit: 'g',
    servingDescription: '1 potong (120g)',
  },
  {
    name: 'Ayam Geprek',
    category: 'lauk',
    calories: 350,
    protein: 24,
    carbs: 20,
    fat: 19,
    servingSize: 130,
    servingUnit: 'g',
    servingDescription: '1 porsi (130g)',
  },
  {
    name: 'Ayam Kecap',
    category: 'lauk',
    calories: 230,
    protein: 22,
    carbs: 10,
    fat: 11,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Daging Kambing Goreng',
    category: 'lauk',
    calories: 270,
    protein: 25,
    carbs: 2,
    fat: 18,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Bebek Goreng',
    category: 'lauk',
    calories: 340,
    protein: 24,
    carbs: 5,
    fat: 25,
    servingSize: 120,
    servingUnit: 'g',
    servingDescription: '1 potong (120g)',
  },
  {
    name: 'Perkedel Kentang',
    category: 'lauk',
    calories: 140,
    protein: 5,
    carbs: 18,
    fat: 6,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 buah (60g)',
  },
  {
    name: 'Bakso Goreng',
    category: 'lauk',
    calories: 80,
    protein: 5,
    carbs: 5,
    fat: 4,
    servingSize: 30,
    servingUnit: 'g',
    servingDescription: '1 buah besar (30g)',
  },
  {
    name: 'Nugget Ayam',
    category: 'lauk',
    calories: 230,
    protein: 14,
    carbs: 16,
    fat: 13,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '5 buah (100g)',
  },
  {
    name: 'Sosis Goreng',
    category: 'lauk',
    calories: 180,
    protein: 7,
    carbs: 6,
    fat: 15,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '2 buah (60g)',
  },
  {
    name: 'Semur Daging',
    category: 'lauk',
    calories: 240,
    protein: 22,
    carbs: 12,
    fat: 12,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Pindang Ikan',
    category: 'lauk',
    calories: 160,
    protein: 24,
    carbs: 3,
    fat: 6,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Ikan Asin Goreng',
    category: 'lauk',
    calories: 120,
    protein: 20,
    carbs: 0,
    fat: 5,
    servingSize: 30,
    servingUnit: 'g',
    servingDescription: '1 potong kecil (30g)',
  },
  {
    name: 'Pepes Ikan',
    category: 'lauk',
    calories: 170,
    protein: 24,
    carbs: 4,
    fat: 7,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 bungkus (100g)',
  },
  {
    name: 'Paru Goreng',
    category: 'lauk',
    calories: 210,
    protein: 20,
    carbs: 4,
    fat: 13,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 potong (80g)',
  },
  {
    name: 'Hati Ayam Goreng',
    category: 'lauk',
    calories: 180,
    protein: 18,
    carbs: 3,
    fat: 11,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '2 buah (80g)',
  },
  {
    name: 'Dendeng Sapi',
    category: 'lauk',
    calories: 250,
    protein: 28,
    carbs: 8,
    fat: 12,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 lembar (60g)',
  },
  {
    name: 'Opor Ayam',
    category: 'lauk',
    calories: 280,
    protein: 22,
    carbs: 6,
    fat: 19,
    servingSize: 120,
    servingUnit: 'g',
    servingDescription: '1 potong dengan kuah (120g)',
  },
  {
    name: 'Tongseng Kambing',
    category: 'lauk',
    calories: 260,
    protein: 22,
    carbs: 8,
    fat: 16,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Ikan Salmon Panggang',
    category: 'lauk',
    calories: 208,
    protein: 28,
    carbs: 0,
    fat: 11,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 fillet (100g)',
  },

  // ============================================================
  // SAYUR (tambahan ~18 item, dari 7 → ~25)
  // ============================================================
  {
    name: 'Sayur Sop',
    category: 'sayur',
    calories: 80,
    protein: 4,
    carbs: 10,
    fat: 2,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (200g)',
  },
  {
    name: 'Tumis Kangkung Terasi',
    category: 'sayur',
    calories: 90,
    protein: 4,
    carbs: 8,
    fat: 4,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Oseng Tempe Kacang',
    category: 'sayur',
    calories: 180,
    protein: 10,
    carbs: 14,
    fat: 9,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Tumis Buncis',
    category: 'sayur',
    calories: 70,
    protein: 3,
    carbs: 9,
    fat: 3,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Tumis Bayam',
    category: 'sayur',
    calories: 60,
    protein: 3,
    carbs: 7,
    fat: 2,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Lalapan Mentah',
    category: 'sayur',
    calories: 30,
    protein: 2,
    carbs: 5,
    fat: 0,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 porsi (100g)',
  },
  {
    name: 'Tumis Tauge',
    category: 'sayur',
    calories: 55,
    protein: 3,
    carbs: 6,
    fat: 2,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Urap Sayur',
    category: 'sayur',
    calories: 120,
    protein: 4,
    carbs: 10,
    fat: 7,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Tumis Wortel Buncis',
    category: 'sayur',
    calories: 75,
    protein: 2,
    carbs: 11,
    fat: 3,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Oseng Pare',
    category: 'sayur',
    calories: 65,
    protein: 2,
    carbs: 8,
    fat: 3,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Tumis Tahu Sayur',
    category: 'sayur',
    calories: 130,
    protein: 8,
    carbs: 8,
    fat: 7,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Acar Kuning',
    category: 'sayur',
    calories: 45,
    protein: 1,
    carbs: 9,
    fat: 1,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 porsi (100g)',
  },
  {
    name: 'Tumis Jamur Tiram',
    category: 'sayur',
    calories: 80,
    protein: 3,
    carbs: 9,
    fat: 4,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Sayur Asem Betawi',
    category: 'sayur',
    calories: 90,
    protein: 4,
    carbs: 13,
    fat: 2,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (200g)',
    regionTag: 'Betawi',
  },
  {
    name: 'Oseng Tahu Tempe',
    category: 'sayur',
    calories: 160,
    protein: 11,
    carbs: 10,
    fat: 9,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Tumis Terong',
    category: 'sayur',
    calories: 75,
    protein: 2,
    carbs: 9,
    fat: 4,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },
  {
    name: 'Sayur Nangka',
    category: 'sayur',
    calories: 110,
    protein: 3,
    carbs: 16,
    fat: 4,
    servingSize: 200,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (200g)',
  },
  {
    name: 'Tumis Kacang Panjang',
    category: 'sayur',
    calories: 70,
    protein: 3,
    carbs: 9,
    fat: 3,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi (150g)',
  },

  // ============================================================
  // GORENGAN (tambahan ~18 item, dari 6 → ~24)
  // ============================================================
  {
    name: 'Pisang Goreng',
    category: 'gorengan',
    calories: 150,
    protein: 1,
    carbs: 28,
    fat: 5,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 buah (80g)',
  },
  {
    name: 'Ubi Goreng',
    category: 'gorengan',
    calories: 170,
    protein: 2,
    carbs: 32,
    fat: 5,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Singkong Goreng',
    category: 'gorengan',
    calories: 200,
    protein: 2,
    carbs: 38,
    fat: 6,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Tempe Mendoan',
    category: 'gorengan',
    calories: 180,
    protein: 10,
    carbs: 14,
    fat: 10,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 lembar (80g)',
    regionTag: 'Banyumas',
  },
  {
    name: 'Tahu Isi',
    category: 'gorengan',
    calories: 130,
    protein: 7,
    carbs: 10,
    fat: 7,
    servingSize: 70,
    servingUnit: 'g',
    servingDescription: '1 buah (70g)',
  },
  {
    name: 'Bakwan Jagung',
    category: 'gorengan',
    calories: 110,
    protein: 3,
    carbs: 14,
    fat: 5,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '1 buah (50g)',
  },
  {
    name: 'Bakwan Sayur',
    category: 'gorengan',
    calories: 95,
    protein: 3,
    carbs: 12,
    fat: 4,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '1 buah (50g)',
  },
  {
    name: 'Cireng',
    category: 'gorengan',
    calories: 130,
    protein: 2,
    carbs: 22,
    fat: 4,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '3 buah (60g)',
    regionTag: 'Sunda',
  },
  {
    name: 'Batagor',
    category: 'gorengan',
    calories: 200,
    protein: 10,
    carbs: 18,
    fat: 10,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 porsi (100g)',
    regionTag: 'Sunda',
  },
  {
    name: 'Risoles',
    category: 'gorengan',
    calories: 180,
    protein: 6,
    carbs: 20,
    fat: 9,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 buah (80g)',
  },
  {
    name: 'Kroket Kentang',
    category: 'gorengan',
    calories: 160,
    protein: 5,
    carbs: 20,
    fat: 7,
    servingSize: 70,
    servingUnit: 'g',
    servingDescription: '1 buah (70g)',
  },
  {
    name: 'Martabak Telur',
    category: 'gorengan',
    calories: 280,
    protein: 12,
    carbs: 24,
    fat: 15,
    servingSize: 120,
    servingUnit: 'g',
    servingDescription: '1 potong (120g)',
  },
  {
    name: 'Lumpia Goreng',
    category: 'gorengan',
    calories: 150,
    protein: 6,
    carbs: 16,
    fat: 7,
    servingSize: 70,
    servingUnit: 'g',
    servingDescription: '1 buah (70g)',
  },
  {
    name: 'Combro',
    category: 'gorengan',
    calories: 140,
    protein: 4,
    carbs: 20,
    fat: 6,
    servingSize: 70,
    servingUnit: 'g',
    servingDescription: '1 buah (70g)',
    regionTag: 'Sunda',
  },
  {
    name: 'Misro',
    category: 'gorengan',
    calories: 145,
    protein: 2,
    carbs: 25,
    fat: 5,
    servingSize: 70,
    servingUnit: 'g',
    servingDescription: '1 buah (70g)',
    regionTag: 'Sunda',
  },
  {
    name: 'Tahu Bulat Goreng',
    category: 'gorengan',
    calories: 90,
    protein: 6,
    carbs: 4,
    fat: 6,
    servingSize: 40,
    servingUnit: 'g',
    servingDescription: '3 buah (40g)',
  },
  {
    name: 'Panada',
    category: 'gorengan',
    calories: 210,
    protein: 7,
    carbs: 28,
    fat: 9,
    servingSize: 90,
    servingUnit: 'g',
    servingDescription: '1 buah (90g)',
    regionTag: 'Manado',
  },
  {
    name: 'Pastel Goreng',
    category: 'gorengan',
    calories: 195,
    protein: 6,
    carbs: 22,
    fat: 10,
    servingSize: 85,
    servingUnit: 'g',
    servingDescription: '1 buah (85g)',
  },

  // ============================================================
  // SUP & KUAH (tambahan ~18 item, dari 7 → ~25)
  // ============================================================
  {
    name: 'Soto Mie',
    category: 'sup_kuah',
    calories: 320,
    protein: 14,
    carbs: 40,
    fat: 11,
    servingSize: 350,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (350g)',
    regionTag: 'Bogor',
  },
  {
    name: 'Soto Lamongan',
    category: 'sup_kuah',
    calories: 280,
    protein: 18,
    carbs: 28,
    fat: 10,
    servingSize: 350,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (350g)',
    regionTag: 'Jawa Timur',
  },
  {
    name: 'Soto Bandung',
    category: 'sup_kuah',
    calories: 240,
    protein: 16,
    carbs: 22,
    fat: 9,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
    regionTag: 'Sunda',
  },
  {
    name: 'Sop Iga Sapi',
    category: 'sup_kuah',
    calories: 350,
    protein: 24,
    carbs: 12,
    fat: 22,
    servingSize: 350,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (350g)',
  },
  {
    name: 'Konro Bakar',
    category: 'sup_kuah',
    calories: 380,
    protein: 26,
    carbs: 10,
    fat: 26,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 porsi (300g)',
    regionTag: 'Makassar',
  },
  {
    name: 'Coto Makassar',
    category: 'sup_kuah',
    calories: 320,
    protein: 22,
    carbs: 14,
    fat: 20,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
    regionTag: 'Makassar',
  },
  {
    name: 'Gulai Ayam',
    category: 'sup_kuah',
    calories: 300,
    protein: 20,
    carbs: 8,
    fat: 22,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 porsi (250g)',
  },
  {
    name: 'Gulai Ikan',
    category: 'sup_kuah',
    calories: 260,
    protein: 22,
    carbs: 7,
    fat: 17,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 porsi (250g)',
  },
  {
    name: 'Sop Kambing',
    category: 'sup_kuah',
    calories: 290,
    protein: 22,
    carbs: 8,
    fat: 19,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
  },
  {
    name: 'Pho Ayam',
    category: 'sup_kuah',
    calories: 310,
    protein: 20,
    carbs: 40,
    fat: 7,
    servingSize: 400,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (400g)',
  },
  {
    name: 'Laksa',
    category: 'sup_kuah',
    calories: 380,
    protein: 16,
    carbs: 45,
    fat: 16,
    servingSize: 400,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (400g)',
  },
  {
    name: 'Sop Baso Tahu',
    category: 'sup_kuah',
    calories: 220,
    protein: 12,
    carbs: 22,
    fat: 9,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
  },
  {
    name: 'Mie Bakso Kuah',
    category: 'sup_kuah',
    calories: 350,
    protein: 15,
    carbs: 48,
    fat: 11,
    servingSize: 400,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (400g)',
  },
  {
    name: 'Tekwan',
    category: 'sup_kuah',
    calories: 240,
    protein: 14,
    carbs: 28,
    fat: 8,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
    regionTag: 'Palembang',
  },
  {
    name: 'Pindang Patin',
    category: 'sup_kuah',
    calories: 210,
    protein: 22,
    carbs: 8,
    fat: 10,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
    regionTag: 'Palembang',
  },
  {
    name: 'Tom Yam Ayam',
    category: 'sup_kuah',
    calories: 180,
    protein: 16,
    carbs: 10,
    fat: 8,
    servingSize: 300,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (300g)',
  },
  {
    name: 'Sup Jagung',
    category: 'sup_kuah',
    calories: 130,
    protein: 5,
    carbs: 22,
    fat: 3,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 mangkuk (250g)',
  },
  {
    name: 'Garang Asem Ayam',
    category: 'sup_kuah',
    calories: 220,
    protein: 18,
    carbs: 8,
    fat: 13,
    servingSize: 250,
    servingUnit: 'g',
    servingDescription: '1 bungkus (250g)',
    regionTag: 'Jawa Tengah',
  },

  // ============================================================
  // CAMILAN (tambahan ~22 item, dari 6 → ~28)
  // ============================================================
  {
    name: 'Martabak Manis Coklat',
    category: 'camilan',
    calories: 350,
    protein: 8,
    carbs: 48,
    fat: 15,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Martabak Manis Keju',
    category: 'camilan',
    calories: 380,
    protein: 10,
    carbs: 46,
    fat: 18,
    servingSize: 100,
    servingUnit: 'g',
    servingDescription: '1 potong (100g)',
  },
  {
    name: 'Donat Gula',
    category: 'camilan',
    calories: 260,
    protein: 5,
    carbs: 36,
    fat: 11,
    servingSize: 80,
    servingUnit: 'g',
    servingDescription: '1 buah (80g)',
  },
  {
    name: 'Onde-onde',
    category: 'camilan',
    calories: 170,
    protein: 4,
    carbs: 28,
    fat: 5,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 buah besar (60g)',
  },
  {
    name: 'Dadar Gulung',
    category: 'camilan',
    calories: 140,
    protein: 3,
    carbs: 22,
    fat: 5,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 buah (60g)',
  },
  {
    name: 'Serabi',
    category: 'camilan',
    calories: 130,
    protein: 3,
    carbs: 22,
    fat: 4,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 buah (60g)',
  },
  {
    name: 'Kue Cubir',
    category: 'camilan',
    calories: 120,
    protein: 3,
    carbs: 20,
    fat: 4,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '3 buah (50g)',
  },
  {
    name: 'Apem',
    category: 'camilan',
    calories: 115,
    protein: 3,
    carbs: 22,
    fat: 2,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '1 buah (50g)',
  },
  {
    name: 'Getuk',
    category: 'camilan',
    calories: 140,
    protein: 1,
    carbs: 32,
    fat: 2,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 potong (60g)',
  },
  {
    name: 'Putu Ayu',
    category: 'camilan',
    calories: 125,
    protein: 2,
    carbs: 22,
    fat: 4,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '1 buah (50g)',
  },
  {
    name: 'Lemper',
    category: 'camilan',
    calories: 160,
    protein: 5,
    carbs: 28,
    fat: 4,
    servingSize: 70,
    servingUnit: 'g',
    servingDescription: '1 buah (70g)',
  },
  {
    name: 'Nagasari',
    category: 'camilan',
    calories: 130,
    protein: 2,
    carbs: 26,
    fat: 3,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 buah (60g)',
  },
  {
    name: 'Wajik',
    category: 'camilan',
    calories: 180,
    protein: 2,
    carbs: 38,
    fat: 3,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 potong (60g)',
  },
  {
    name: 'Cenil',
    category: 'camilan',
    calories: 110,
    protein: 1,
    carbs: 26,
    fat: 1,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 porsi (60g)',
  },
  {
    name: 'Kue Lapis',
    category: 'camilan',
    calories: 150,
    protein: 2,
    carbs: 30,
    fat: 3,
    servingSize: 60,
    servingUnit: 'g',
    servingDescription: '1 potong (60g)',
  },
  {
    name: 'Kurma',
    category: 'camilan',
    calories: 120,
    protein: 1,
    carbs: 32,
    fat: 0,
    servingSize: 40,
    servingUnit: 'g',
    servingDescription: '4 buah (40g)',
  },
  {
    name: 'Kacang Tanah Goreng',
    category: 'camilan',
    calories: 290,
    protein: 13,
    carbs: 10,
    fat: 24,
    servingSize: 50,
    servingUnit: 'g',
    servingDescription: '1 genggam (50g)',
  },
  {
    name: 'Keripik Tempe',
    category: 'camilan',
    calories: 200,
    protein: 10,
    carbs: 18,
    fat: 10,
    servingSize: 40,
    servingUnit: 'g',
    servingDescription: '1 bungkus kecil (40g)',
  },
  {
    name: 'Keripik Singkong',
    category: 'camilan',
    calories: 220,
    protein: 1,
    carbs: 38,
    fat: 8,
    servingSize: 40,
    servingUnit: 'g',
    servingDescription: '1 bungkus kecil (40g)',
  },
  {
    name: 'Keripik Pisang',
    category: 'camilan',
    calories: 210,
    protein: 1,
    carbs: 34,
    fat: 8,
    servingSize: 40,
    servingUnit: 'g',
    servingDescription: '1 bungkus kecil (40g)',
  },
  {
    name: 'Buah Potong Segar',
    category: 'camilan',
    calories: 80,
    protein: 1,
    carbs: 20,
    fat: 0,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 porsi campur (150g)',
  },
  {
    name: 'Yogurt Plain',
    category: 'camilan',
    calories: 100,
    protein: 6,
    carbs: 12,
    fat: 3,
    servingSize: 150,
    servingUnit: 'g',
    servingDescription: '1 cup (150g)',
  },

  // ============================================================
  // MINUMAN (tambahan ~18 item, dari 5 → ~23)
  // ============================================================
  {
    name: 'Es Jeruk',
    category: 'minuman',
    calories: 90,
    protein: 1,
    carbs: 22,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Jus Mangga',
    category: 'minuman',
    calories: 130,
    protein: 1,
    carbs: 32,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Jus Semangka',
    category: 'minuman',
    calories: 80,
    protein: 1,
    carbs: 20,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Jus Jambu',
    category: 'minuman',
    calories: 95,
    protein: 1,
    carbs: 23,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Susu Sapi Full Cream',
    category: 'minuman',
    calories: 150,
    protein: 8,
    carbs: 12,
    fat: 8,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Susu Skim',
    category: 'minuman',
    calories: 85,
    protein: 8,
    carbs: 12,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Teh Tarik',
    category: 'minuman',
    calories: 130,
    protein: 3,
    carbs: 20,
    fat: 4,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Kopi Hitam Tanpa Gula',
    category: 'minuman',
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    servingSize: 200,
    servingUnit: 'ml',
    servingDescription: '1 cangkir (200ml)',
  },
  {
    name: 'Kopi Susu Kental Manis',
    category: 'minuman',
    calories: 180,
    protein: 3,
    carbs: 28,
    fat: 6,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Es Teh Tawar',
    category: 'minuman',
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Minuman Isotonik',
    category: 'minuman',
    calories: 60,
    protein: 0,
    carbs: 15,
    fat: 0,
    servingSize: 350,
    servingUnit: 'ml',
    servingDescription: '1 botol (350ml)',
  },
  {
    name: 'Air Putih',
    category: 'minuman',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
  {
    name: 'Es Campur',
    category: 'minuman',
    calories: 220,
    protein: 3,
    carbs: 45,
    fat: 4,
    servingSize: 300,
    servingUnit: 'ml',
    servingDescription: '1 mangkuk (300ml)',
  },
  {
    name: 'Es Doger',
    category: 'minuman',
    calories: 250,
    protein: 4,
    carbs: 48,
    fat: 5,
    servingSize: 300,
    servingUnit: 'ml',
    servingDescription: '1 mangkuk (300ml)',
    regionTag: 'Sunda',
  },
  {
    name: 'Wedang Jahe',
    category: 'minuman',
    calories: 60,
    protein: 0,
    carbs: 15,
    fat: 0,
    servingSize: 200,
    servingUnit: 'ml',
    servingDescription: '1 gelas (200ml)',
  },
  {
    name: 'Bajigur',
    category: 'minuman',
    calories: 120,
    protein: 2,
    carbs: 22,
    fat: 3,
    servingSize: 200,
    servingUnit: 'ml',
    servingDescription: '1 gelas (200ml)',
    regionTag: 'Sunda',
  },
  {
    name: 'Bandrek',
    category: 'minuman',
    calories: 90,
    protein: 1,
    carbs: 20,
    fat: 2,
    servingSize: 200,
    servingUnit: 'ml',
    servingDescription: '1 gelas (200ml)',
    regionTag: 'Sunda',
  },
  {
    name: 'Jus Alpukat Susu',
    category: 'minuman',
    calories: 220,
    protein: 4,
    carbs: 20,
    fat: 14,
    servingSize: 250,
    servingUnit: 'ml',
    servingDescription: '1 gelas (250ml)',
  },
];

// RINGKASAN JUMLAH PER KATEGORI:
// nasi_karbo: +25 item (8 → 33)
// lauk:       +35 item (17 → 52)
// sayur:      +18 item (7 → 25)
// gorengan:   +18 item (6 → 24)
// sup_kuah:   +18 item (7 → 25)
// camilan:    +22 item (6 → 28)
// minuman:    +18 item (5 → 23)
// TOTAL TAMBAHAN: 154 item baru
// TOTAL KESELURUHAN: ~210 item (dari 56 sebelumnya)
